# Generated by Django 3.1 on 2020-08-29 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('body', models.TextField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('a', models.CharField(default='', max_length=200, unique=True)),
                ('b', models.CharField(default='', max_length=200, unique=True)),
                ('c', models.CharField(default='', max_length=200, unique=True)),
                ('d', models.CharField(default='', max_length=200, unique=True)),
                ('answer', models.CharField(max_length=1)),
                ('marks', models.IntegerField(default=0)),
                ('story', models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='multi_choice.story_text')),
            ],
        ),
    ]
