# Generated by Django 3.1 on 2020-08-29 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_choice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='story',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='multi_choice.story_text'),
        ),
    ]
