# Generated by Django 3.1 on 2020-08-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_choice', '0004_auto_20200830_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='a',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='b',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='c',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='d',
            field=models.CharField(default='', max_length=200),
        ),
    ]
